overwatchdb/views.py
from flask import Blueprint, render_template
import json
import traceback

import overwatchdb.models as models

views = Blueprint('views', __name__)


@views.route('/')
def index():
    """ Returns Welcome Page """
    return render_template('index.html')


@views.route('/tests/run')
def run_tests():
    """ Runs all the unittests and returns the text result with verbosity 2 """
    import overwatchdb.test_runner as test_runner
    return test_runner.run_tests()


@views.route('/api/players', methods=['GET'])
def players():
    """ Returns Players Page """
    data = models.Player.query.all()
    if not data:
        return render_template('404.html', thing='Players')
    print(data)
    return render_template('players.html', data=data)


@views.route('/api/players/<int:player_id>', methods=['GET'])
def player(player_id):
    """ Returns Page for a single Player """
    data = models.Player.query.get(player_id)
    if not data:
        return render_template('404.html', thing='Player')
    print(data.url)
    return render_template('players_instance.html', data=data)


@views.route('/api/heroes', methods=['GET'])
def heroes():
    """ Returns Heroes Page """
    data = models.Hero.query.all()
    if not data:
        return render_template('404.html', thing='Heroes')
    print(data)
    return render_template('heroes.html', data=data)


@views.route('/api/heroes/<int:hero_id>', methods=['GET'])
def hero(hero_id):
    """ Returns Page for a single Hero """
    data = models.Hero.query.get(hero_id)
    if not data:
        return render_template('404.html', thing='Hero')
    print(data)
    return render_template('heroes_instance.html', data=data)


@views.route('/api/rewards', methods=['GET'])
def rewards():
    """ Returns Rewards Page """
    data = models.Reward.query.all()
    if not data:
        return render_template('404.html', thing='Rewards')
    print(data)
    return render_template('rewards.html', data=data)


@views.route('/api/rewards/<int:reward_id>', methods=['GET'])
def reward(reward_id):
    """ Returns Page for a single Reward """
    data = models.Reward.query.get(reward_id)
    if not data:
        return render_template('404.html', thing='Reward')
    print(data)
    return render_template('rewards_instance.html', data=data)


@views.route('/api/achievements', methods=['GET'])
def achievements():
    """ Returns Achievements Page """
    data = models.Achievement.query.all()
    if not data:
        return render_template('404.html', thing='Achievements')
    print(data)
    return render_template('achievements.html', data=data)  # id=achievement_id)


@views.route('/api/achievements/<int:achievement_id>', methods=['GET'])
def achievement(achievement_id):
    data = models.Achievement.query.get(achievement_id)
    if not data:
        return render_template('404.html', thing='Achievement')
    print(data)
    return render_template('achievements_instance.html', data=data)


@views.route('/about/')
def about():
    """ Returns Heroes Page """
    return render_template('about.html')

overwatchdb/templates/Achievement.html
{% extends "layout.html" %}


{% block content %}
  <div id="achievements" class="container text-center">
    <br>
    <br>
    <br>
    <div class="row">
        <p style="font-size:40px;color:white" class="text-center"><strong> Achievements<strong></p>
    <hr>

     <p style="font-size:25px;color:white" class="text-center">Anger Management</p><br>
      <a href="AchiHtmls/AngerManagement.html">
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/anger_management.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:black" class="text-center"><strong>Group Health Plan</strong></p><br>
      <a href="AchiHtmls/GroupHealthPlan.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/group_health_plan.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:white" class="text-center"><strong>Huge Rez</strong></p><br>
      <a href="AchiHtmls/HugeRez.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/huge_rez.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:black" class="text-center"><strong>Mine Sweeper</strong></p><br>
      <a href="AchiHtmls/MineSweeper.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/mine_sweeper.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:white" class="text-center"><strong>Simple Geometry</strong></p><br>
      <a href="AchiHtmls/SimpleGeometry.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/simple_geometry.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>


    <div class="row">
      <p style="font-size:25px;color:black" class="text-center"><strong>The Dragon Is Sated</strong></p><br>
      <a href="AchiHtmls/TheDragonIsSated.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/the%20_dragon_is_sated.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
  </div>

{% endblock %}

overwatchdb/templates/Achievements.html
{% extends "layout.html" %}


{% block content %}
<link href="../static/css/achievements.css" rel="stylesheet">
  <div id="achievements" class="container text-center">
    <br>
    <br>
    <br>
    <div class="row">
        <p style="font-size:40px;color:white" class="text-center"><strong> Achievements<strong></p>
    <hr>

     <p style="font-size:25px;color:white" class="text-center">Anger Management</p><br>
      <a href="AchiHtmls/AngerManagement.html">
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/anger_management.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:black" class="text-center"><strong>Group Health Plan</strong></p><br>
      <a href="AchiHtmls/GroupHealthPlan.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/group_health_plan.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:white" class="text-center"><strong>Huge Rez</strong></p><br>
      <a href="AchiHtmls/HugeRez.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/huge_rez.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:black" class="text-center"><strong>Mine Sweeper</strong></p><br>
      <a href="AchiHtmls/MineSweeper.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/mine_sweeper.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>

    <div class="row">
      <p style="font-size:25px;color:white" class="text-center"><strong>Simple Geometry</strong></p><br>
      <a href="AchiHtmls/SimpleGeometry.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/simple_geometry.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <hr>


    <div class="row">
      <p style="font-size:25px;color:black" class="text-center"><strong>The Dragon Is Sated</strong></p><br>
      <a href="AchiHtmls/TheDragonIsSated.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/achi_pic/the%20_dragon_is_sated.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
  </div>

{% endblock %}

overwatchdb/templates/Achievements_Instance.html
<!-- Extend base.html here? -->
{% extend 'layout.html' %}
{%block content%}
<!-- Need to change the art thing below -->
<link rel="stylesheet" type="text/css" href="../static/css/achievements.css">
<div id="instance-main">
	<h1><strong>{{Achievements_Instance.name}}</strong></h1>
	<img src=
		{% if Achievements_Instance.art.lower() != "none" %}
			{{ Achievements_Instance.art }}
		{% else %}
			{{"https://wiki.gamedetectives.net/images/b/bf/Overwatch_logo.jpg"}}
		{% endif %}
	class="img-fluid">

	<h4><strong>Name: </strong>{{Achievements_Instance.name}}</h4>
	<h4><strong>Description: </strong>{{Achievements_Instance.description}}</h4>
	<h4><strong>Hero: </strong>{{Achievements_Instance.hero.name}}</h4>
	<h4><strong>Reward: </strong>{{Achievements_Instance.reward.name}}</h4>
</div>

{% endblock%}

overwatchdb/templates/Heroes.html
{% extends "layout.html" %}


{% block content %}
<link href="../static/css/heroes.css" rel="stylesheet">
  <div id="heroes" class="container text-center">
    <br>
    <br>
    <br>
    <div class="row">
      <p style="font-size:30px;color:black" class="text-center"><strong>Mercy</strong></p><br>
      <a href="{{ url_for('views.hero',hero_name='Mercy') }}">
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/hero_pic/MERCY.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:black" class="text-center"><strong>Winston</strong></p><br>
      <a href="{{ url_for('views.hero',hero_name='Winston') }}"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/hero_pic/WINSTON.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:black" class="text-center"><strong>Hanzo</strong></p><br>
      <a href="{{ url_for('views.hero',hero_name='Hanzo') }}">
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/hero_pic/HANZO.jpg" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
  </div>
{% endblock %}

overwatchdb/templates/Heroes_Instance.html
<!-- Extend base.html here? -->
{% extend 'layout.html' %}
{%block content%}
<!-- Need to change the art thing below -->
<link rel="stylesheet" href="../static/css/heroes.css">
<div id="instance-main">
	<h1><strong>{{Heroes_Instance.name}}</strong></h1>
	<img src=
		{% if Heroes_Instance.art.lower() != "none" %}
			{{ Heroes_Instance.art }}
		{% else %}
			{{"https://wiki.gamedetectives.net/images/b/bf/Overwatch_logo.jpg"}}
		{% endif %}
	class="img-fluid">

	<h4><strong>Real Name: </strong>{{Heroes_Instance.real_name}}</h4>
	<h4><strong>Description: </strong>{{Heroes_Instance.description}}</h4>
	<h4><strong>Age: </strong>{{Heroes_Instance.age}}</h4>
	<h4><strong>Difficulty: </strong>{{Heroes_Instance.difficulty}}</h4>
	<h4><strong>Affiliation: </strong>{{Heroes_Instance.affiliation}}</h4>
</div>

{% endblock%}

overwatchdb/templates/Players.html
{% extends "layout.html" %}


{% block content %}
  <link href="../static/css/players.css" rel="stylesheet">
  <div id="players" class="container text-center">
    <br>
    <br>
    <br>
    <div class="row">
      <p style="font-size:30px;color:black" class="text-center"><strong>KAFEEEEEE-2350</strong></p><br>
      <a href="PlayersHtmls/player1.html">
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/Background_pic/Kafeeeeee.png" class="img-circle person" alt="Random Name" width="256" height="256">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:black" class="text-center"><strong>SILKTHREAD-1324</strong></p><br>
      <a href="PlayersHtmls/player2.html"> 
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/Background_pic/Silkthread.png" class="img-circle person" alt="Random Name" width="256" height="256">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:black" class="text-center"><strong>FANCYHAT-4714</strong></p><br>
      <a href="PlayersHtmls/player3.html">
        <img src="https://raw.githubusercontent.com/XS2929/idb/master/static/Background_pic/FancyHat.png" class="img-circle person" alt="Random Name" width="256" height="256">
      </a>
    </div>
{% endblock %}

overwatchdb/templates/Players_Instance.html
<!-- Extend base.html here? -->
{% extend 'layout.html' %}
{%block content%}
<!-- Unsure of how to get data for players based on our json-->
<!-- Need to change the art thing below -->
<link rel="stylesheet" type="text/css" href="../static/css/players.css">
<div id="instance-main">
	<h1><strong>{{Players_Instance.name}}</strong></h1>
	<img src=
		{% if Players_Instance.art.lower() != "none" %}
			{{ Players_Instance.art }}
		{% else %}
			{{"https://wiki.gamedetectives.net/images/b/bf/Overwatch_logo.jpg"}}
		{% endif %}
	class="img-fluid">


</div>

{% endblock%}

overwatchdb/templates/Reward.html
{% extends "layout.html" %}


{% block content %}
  <link href="../static/css/reward.css" rel="stylesheet">
  <div id="reward" class="container text-center">
    <br>
    <br>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Pixel Mercy</strong></p><br>
      <a href="RewardHtmls/Pixel_Mercy.html">
        <img src="../static/Reward_pic/Spray_Mercy_Pixel.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Cute Mercy</strong></p><br>
      <a href="RewardHtmls/Cute_Mercy.html">
        <img src="../static/Reward_pic/Spray_Mercy_Cute.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Pixel Winston</strong></p><br>
      <a href="RewardHtmls/Pixel_Winston.html"> 
        <img src="../static/Reward_pic/Spray_Winston_Pixel.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Cute Winston</strong></p><br>
      <a href="RewardHtmls/Cute_Winston.html">
        <img src="../static/Reward_pic/Spray_Winston_Cute.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Cute Hanzo</strong></p><br>
      <a href="RewardHtmls/Cute_Hanzo.html">
        <img src="../static/Reward_pic/Spray_Hanzo_Cute.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Pixel Hanzo</strong></p><br>
      <a href="RewardHtmls/Pixel_Hanzo.html">
        <img src="../static/Reward_pic/Spray_Hanzo_Pixel.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Beyond the Moon</strong></p><br>
      <a href="RewardHtmls/Beyond_The_Moon.html">
        <img src="../static/Reward_pic/Spray_Beyond_The_Moon.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
  </div>
</body>
{% endblock %}

overwatchdb/templates/Rewards.html
{% extends "layout.html" %}


{% block content %}
  <link href="../static/css/reward.css" rel="stylesheet">
  <div id="reward" class="container text-center">
    <br>
    <br>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Pixel Mercy</strong></p><br>
      <a href="RewardHtmls/Pixel_Mercy.html">
        <img src="../static/images/Reward_pic/Spray_Mercy_Pixel.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Cute Mercy</strong></p><br>
      <a href="RewardHtmls/Cute_Mercy.html">
        <img src="../static/images/Reward_pic/Spray_Mercy_Cute.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Pixel Winston</strong></p><br>
      <a href="RewardHtmls/Pixel_Winston.html"> 
        <img src="../static/images/Reward_pic/Spray_Winston_Pixel.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Cute Winston</strong></p><br>
      <a href="RewardHtmls/Cute_Winston.html">
        <img src="../static/images/reward_pic/Spray_Winston_Cute.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Cute Hanzo</strong></p><br>
      <a href="RewardHtmls/Cute_Hanzo.html">
        <img src="../static/images/reward_pic/Spray_Hanzo_Cute.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Pixel Hanzo</strong></p><br>
      <a href="RewardHtmls/Pixel_Hanzo.html">
        <img src="../static/images/reward_pic/Spray_Hanzo_Pixel.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
    <br>
    <div class="row">
      <p style="font-size:30px;color:blue" class="text-center"><strong>Beyond the Moon</strong></p><br>
      <a href="RewardHtmls/Beyond_The_Moon.html">
        <img src="../static/images/reward_pic/Spray_Beyond_The_Moon.png" class="img-circle person" alt="Random Name" width="500" height="400">
      </a>
    </div>
  </div>

{% endblock %}

overwatchdb/templates/Rewards_Instance.html
<!-- Extend base.html here? -->
{% extend 'layout.html' %}
{%block content%}
<!-- Need to change the art thing below -->
<link rel="stylesheet" type="text/css" href="../static/css/reward.css">
<div id="instance-main">
	<h1><strong>{{Reward_Instance.name}}</strong></h1>
	<img src=
		{% if Reward_Instance.art.lower() != "none" %}
			{{ Reward_Instance.art }}
		{% else %}
			{{"https://wiki.gamedetectives.net/images/b/bf/Overwatch_logo.jpg"}}
		{% endif %}
	class="img-fluid">

	<h4><strong>Name: </strong>{Reward_Instance.name}}</h4>
	<h4><strong>Cost: </strong>{{Reward_Instance.cost.value}}</h4>
	<h4><strong>Type: </strong>{{Reward_Instance.type.name}}</h4>
	<h4><strong>Quality: </strong>{{Reward_Instance.quality.name}}</h4>

</div>

{% endblock%}